version: '2'
services:
   db:
     volumes:
       - pgdata:/var/lib/postgresql/data
     image: postgres
     environment:
       - POSTGRES_USER=olgart
       - POSTGRES_DB=olgart

   app:
     build: ./app/
     volumes:
       - static:/www/static/:ro
       - media:/www/media/
       - ./olgart.json:/olgart.json:ro
       - ./media:/media_backup:ro
#     ports:
#       - "8000:8000"
#     environment:
#       - DJANGODEBUG=1
     env_file:
       - secrets.env
     depends_on:
       - db
   
   proxy:
     build: ./proxy/
     volumes:
       - static:/www/static/:ro
       - media:/www/media/:ro
       - ssl:/etc/nginx/ssl
       - letsencrypt:/etc/letsencrypt
     ports:
       - "80:80"
       - "443:443"
     environment:
       - TZ=Europe/Moscow
       - LE_EMAIL=hombit@olgart.ru
       - NGINX_HOST=olgart.ru
     depends_on:
       - app

volumes:
   static:
   media:
   pgdata:
   ssl:
   letsencrypt:
