version: '2'
services:
   db:
     volumes:
       - pgdata:/var/lib/postgresql/data
     image: postgres
     environment:
       - POSTGRES_USER=olgart
       - POSTGRES_DB=olgart
     restart: always

   app:
     build: ./app/
     volumes:
       - static:/www/static/:ro
       - media:/www/media/
       - ./backup:/backup
     ports:
       - "8000:8000"
     environment:
       - DJANGODEBUG=1
     env_file:
       - secrets.env
     depends_on:
       - db
     restart: always

   backup:
     build: ./app/
     volumes:
       - media:/www/media/:ro
       - ./backup:/backup
     entrypoint: ./docker-backup.sh
     env_file:
       - secrets.env
     depends_on:
       - db
     restart: always

   proxy:
     build: ./proxy/
     volumes:
       - static:/www/static/:ro
       - media:/www/media/:ro
       - ssl:/etc/nginx/ssl
     ports:
       - "80:80"
       - "443:443"
     environment:
       - TZ=Europe/Moscow
       - LE_EMAIL=hombit@olgart.ru
       - NGINX_HOST=dev.olgart.ru
     depends_on:
       - app
     restart: always

volumes:
   static:
   media:
   pgdata:
   ssl:
